export enum Characters {
  BeastTyrant = "Beast Tyrant",
  Berserker = "Berserker",
  Brute = "Brute",
  Cragheart = "Cragheart",
  Doomstalker = "Doomstalker",
  Elementalist = "Elementalist",
  Mindthief = "Mindthief",
  Nightshroud = "Nightshroud",
  Plagueherald = "Plagueherald",
  Quartermaster = "Quartermaster",
  Sawbones = "Sawbones",
  Scoundrels = "Scoundrels",
  Soothsinger = "Soothsinger",
  Spellweaver = "Spellweaver",
  Summoner = "Summoner",
  Sunkeeper = "Sunkeeper",
  Tinkerer = "Tinkerer",
}